### ISSUE TITLE
does it package for Windows ?

### ISSUE THREAD

**Issue by gedw99** [develar/app-builder#12]
Cant see anything in the the code to help with building windows apps.

am i missing something ?

**Comment by develar** [comment]
Nsis builder is a part of electron-builder, not migrated from NodeJS to go.

**Comment by gedw99** [comment]
hey @develar  
thanks for the update.

I am not trying to package electron apps, but actually flutter desktop apps.
https://github.com/go-flutter-desktop/go-flutter
I have it packaging to a .app on darwin.
so i figured i could make a dmg using app-builder.

I also am wishing to try to also package for windows.
