### ISSUE TITLE
Missing LICENSE file in the repo of ver 3.5.12

### ISSUE THREAD

**Issue by itsuki-murata** [develar/app-builder#129]
Currently I'm using app-builder-bin version 3.5.12, but can't find a LICENSE file in the repo of ver 3.5.12.
Could you add the LICENSE file in the repo of ver 3.5.12?
Or is it possible to use the LICENSE file of the latest version as the license for ver 3.5.12?
Thanks in advance.

**Comment by mmaietta** [comment]
I'm not sure it's possible to do so since the 3.5.12 release is a tag, not a branch, so there's no way to edit that commit history and inject a file AFAIK.
