### ISSUE TITLE
Update useragent

### ISSUE THREAD

**Issue by frjonsen** [develar/app-builder#13]
The useragent set by this package is `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"`. As far as I can tell, this is hardcoded and cannot be changed through any option or similar.

Unfortunately, the age of the browser versions that are set is interfering with our corporate proxy, which blocks old browsers. Would it be possible to have the useragent updated to something more modern? As we use this package only indirectly through another ([Electron-Builder](https://github.com/electron-userland/electron-builder)) simply making it customizable would not help us.

One suggestion might be to make some options customizable through environment variables? I suspect that could come in handy for people having other issues than just the useragent.

**Comment by develar** [comment]
Env `DOWNLOADER_USER_AGENT` is added for you. Sorry for delay.
