### ISSUE TITLE
node-dep-tree hangs on windows when using an absolute path

### ISSUE THREAD

**Issue by cdriehuys** [develar/app-builder#2]
I am trying to build an app using electron-builder, and it is hanging. The logs show that it gets stuck after spawning the command:

```
C:\Users\chdrie\Documents\Programs\JavaScript\mas-demo-client\node_modules\app-builder-bin\win\x64\app-builder.exe node-dep-tree --dir C:\Users\chdrie\Documents\Programs\JavaScript\mas-demo-client
```

Running this command in a separate powershell window confirms that it does indeed hang. However, if I pass a relative path to the `--dir` flag, the command succeeds. To clarify, if I `cd \`, the following command works:

```
C:\Users\chdrie\Documents\Programs\JavaScript\mas-demo-client\node_modules\app-builder-bin\win\x64\app-builder.exe node-dep-tree --dir Users\chdrie\Documents\Programs\JavaScript\mas-demo-client
```

Any assistance would be appreciated.

**Comment by terorie** [comment]
Okay, I am 99% sure that the hang occurs here: https://github.com/develar/app-builder/blob/6900b354ea36e2e68800d34ef939a37908127622/pkg/nodeModules/tree.go#L257

**Comment by terorie** [comment]
Yay! I fixed it: https://github.com/develar/app-builder/pull/3

Please pull asap.
