### ISSUE TITLE
Under which license is app-builder?

### ISSUE THREAD

**Issue by passy** [develar/app-builder#27]
Hi! 👋

I'd love to make a contribution but would quite like to know which license the code in this repo is under. Mind adding a `LICENSE` file? :)

Cheers!

**Comment by passy** [comment]
Brilliant! Thanks for the quick turnaround!

**Comment by RobertBorg** [comment]
It's great that there is a LICENSE file but could you include it in the binary distribution as well?
https://unpkg.com/browse/app-builder-bin@latest/
