### ISSUE TITLE
Encode plist files in XML instead of binary to mitigate App Store build crashes

### ISSUE THREAD

**Issue by sangeeth96** [develar/app-builder#31]
I'm using `electron-builder` to build distributables for my Electron app. Currently, `app-builder` is producing `Info.plist` files in binary format. This seems to be causing `mas` and `mas-dev` builds to crash at runtime. I'm not sure if there's any official documentation that states MAS builds should have XML formatted plists, but it is mentioned as necessary for entitlement `plist` files for notarization ([see here](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues)).

I've detailed the steps I've taken to get working `mas`/`mas-dev` builds here: https://github.com/electron/electron-osx-sign/issues/223#issuecomment-611070794.

Changing the following:
https://github.com/develar/app-builder/blob/0c35a476cb6721132fdd0de733b50aa3fc8bf72c/pkg/plist/plist.go#L47

to have `plist.XMLFormat` passed instead should do the trick, I hope.

**Comment by wgcv** [comment]
Please this change is very importan there are a lot of issues about this @develar

**Comment by sangeeth96** [comment]
This should be fixed now. Thanks @wgcv!
