### ISSUE TITLE
Microsoft Defender detected "Trojan:Win32/Fuerboos.A!cl" in app-builder.exe

### ISSUE THREAD

**Issue by Deco** [develar/app-builder#32]
![image](https://user-images.githubusercontent.com/95221/79585333-3e198900-8102-11ea-84c0-80c7e1324ec9.png)

Just FYI. Either Microsoft Builder is confused, or someone has uploaded something malicious to npm.

**Comment by Niquolas** [comment]
See: https://www.virustotal.com/gui/file/865ac2546cd8019ed2774e3783dcc311d35ebf962f39fd085630186e7ffa008f/detection

**Comment by Niquolas** [comment]
False alarm: https://github.com/electron-userland/electron-builder/issues/4886#issuecomment-616085789

**Comment by mikekreeki** [comment]
Just for reference, getting the same alert from our company-wide Carbon Black Predictive Security Cloud. Can test when an update is released.

**Comment by nicely** [comment]
![WhatsApp Image 2020-04-27 at 16 47 32](https://user-images.githubusercontent.com/6550788/80435776-4f0c8c00-88b2-11ea-9ecd-640d68f0181b.jpeg)
Same here...

**Comment by koenoe** [comment]
+1

**Comment by develar** [comment]
electron-builder 22.6.0 published. Rebuilt with a new Go version.

**Comment by jkoenig134** [comment]
@develar not it is another trojan.
![image](https://user-images.githubusercontent.com/33655937/80582343-d0793100-8a0e-11ea-83d1-4ad2187ce354.png)

**Comment by nicely** [comment]
> electron-builder 22.6.0 published. Rebuilt with a new Go version.

What is mean that  **new GO** version?

**Comment by nicely** [comment]
Still TROJAN...

I just removed **node_modules** and upgraded to version 22.6.0 and checked the folder `node_modules/app-builder-bin/win/ia32` this time there is not only 1 .exe file there are 3 files in there one of them zipped as you can see below screenshot and all .exe files mentioned as TROJAN. Am I doing wrong something?

<img width="638" alt="Screen Shot 2020-05-01 at 00 25 39" src="https://user-images.githubusercontent.com/6550788/80790006-8beeb200-8b42-11ea-9eb8-3a14d45db57a.png">
<img width="1277" alt="Screen Shot 2020-05-01 at 00 24 31" src="https://user-images.githubusercontent.com/6550788/80790012-8ee9a280-8b42-11ea-91b0-605b86de9464.png">

**Comment by koenoe** [comment]
+1

**Comment by fedot** [comment]
The issue is still here

- ia32 binaries published to npm are infrected (several versions backwards).
- Building binary locally produce different checksum that the binary published to npm
- package.json in the repository steted lower version than the published version? Seriously?
