### ISSUE TITLE
Trojan:Win32/Woreflint.A!cl: app-builder copy.exe triggering Windows Defender

### ISSUE THREAD

**Issue by adam-lynch** [develar/app-builder#36]
This could easily be a duplicate of #33 but the Trojan name is different (plus there's a lot of noise in that issue).

Reproduce: https://github.com/adam-lynch/app-builder-bin-trojan-issue

app-builder-bin version: 3.5.8.
Node: 10.18.0.
npm: 6.13.4.
OS: Windows 10 Pro Insider Preview Build 19613.rs_prerelease.200417-1557.

Windows Defender screenshot:

![image](https://user-images.githubusercontent.com/1427241/81582169-9b25f900-93a7-11ea-8a79-60748795aeb9.png)

The quarantined file is `app-builder-bin\win\ia32\app-builder copy.exe`

**Comment by jrcharney** [comment]
Sounds familiar to #33 
Quarantine seems ideal for the moment until someone at NPM can bop @develar on the head and get him to delete that dangerous zip file.

Best advice: Don't open it (obviously).

**Comment by develar** [comment]
Duplicates #33
