### ISSUE TITLE
app-builder.exe reporting a virus

### ISSUE THREAD

**Issue by awjreynolds** [develar/app-builder#43]
![image](https://user-images.githubusercontent.com/1948692/93501128-eed3c080-f90c-11ea-92a9-a748b1394659.png)
Windows exe is reporting a virus.

**Comment by mimi89999** [comment]
Probably a false positive due to some bad heuristics. Maybe a malware was using parts of in. Could you please share the hash of the file or even upload it?

**Comment by develar** [comment]
It is false positive. To avoid such issues, new release of app-builder for Windows being produced not on macOS, but on Windows 10.
