### ISSUE TITLE
handle 404 cases caused by using electron mirror

### ISSUE THREAD

**Issue by bytemain** [develar/app-builder#73]
if we want to download electron 14.2.5 binaries, and donot set mirror: the code in <https://github.com/develar/app-builder/blob/master/pkg/electron/electronDownloader.go#L85> will use the url: `https://github.com/electron/electron/releases/download/v`,and the final result is `https://github.com/electron/electron/releases/download/v14.2.5/xxxxxxx.zip`

if we have a custom mirror: `https://npmmirror.com/mirrors/electron`

the code will result the url: `https://npmmirror.com/mirrors/electron/14.2.5` <- this is a 404 url

so we need set the mirror to: `https://npmmirror.com/mirrors/electron/v`, and this will result the electron postinstall script download a 404...

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/13938334/152747538-08e445a2-29cd-4c30-9b80-f59c9df45504.png">

first, nowadays, electron's release all use `vA.B.C` versions, so the download link is: `https://github.com/electron/electron/releases/download/v18.0.0-alpha.1/electron-v18.0.0-alpha.1-darwin-arm64-dsym.zip`

this is how `@electron/get` handle it:
1. get base url without the suffix `/v`
https://github.com/electron/get/blob/main/src/artifact-utils.ts#L45
2. normalize version with a prefix `v`
https://github.com/electron/get/blob/b5a4b714538838f27cb1b65fcee27b1abaac013a/src/utils.ts#L32

**Comment by BlackHole1** [comment]
Temp Fix:

```
ELECTRON_MIRROR=https://cdn.npmmirror.com/binaries/electron/v
ELECTRON_CUSTOM_DIR="{{ version }}"
```

**Comment by byzhangkui** [comment]
> ```ini
> {{ version }}
> ```

app-builder does not know the `{{ version }}` placeholder. cannot work correctly.

**Comment by byzhangkui** [comment]
> Temp Fix:
> 
> ```ini
> ELECTRON_MIRROR=https://cdn.npmmirror.com/binaries/electron/v
> ELECTRON_CUSTOM_DIR="{{ version }}"
> ```

app-builder does not know the {{ version }} placeholder. cannot work correctly.

**Comment by BlackHole1** [comment]
> > ```ini
> > {{ version }}
> > ```
> 
> app-builder does not know the `{{ version }}` placeholder. cannot work correctly.

The `ELECTRON_CUSTOM_DIR` is for `@electron/get` use.
